blank_issues_enabled: true
contact_links:
  - name: Gods Support
    url: https://t.me/Goduserbot_support
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://MRINVISIBLE_OFFICIAL/
    about: Documentation for getting started with bot.
